### ISSUE TITLE
Standards and Specifications Scope - Sign Off Required

### ISSUE THREAD

**Issue by Consianimis** [ethereum-oasis/baseline-roadmap#115]
## Objective
The purpose of this issue is: 
1) to establish expected standards and specifications deliverables
2) to articulate the scope of work for those deliverables.

The sign off of 1) and 2) by the specs working group will initiate the formal kick off of specifications and Oasis standards writing activities. 

## Deliverables
* One Oasis standard - Two parts:
    * Baseline CORE Spec document: describes the minimum required to implement the protocol so that two systems of record can baseline and maintain baseline-compliance.
    * Baseline API Spec document: describes the Baseline programming interface and expected behaviors of all instances of this interface.
* One Mainnet Specification:
    * Mainnet Spec document: describes the properties and qualities of a singleton state machine used as an enterprise public common frame of reference.

## Scope
* Baseline CORE Spec document
<table>
<tr>
    <th>Component</th>
    <th>Component Description</th>
    <th>Proposed Abstraction level</th>
  </tr>
  <tr>
    <td>API Layer</td>
    <td>Reference Baseline API Spec</td>
    <td>See Baseline API Spec document.</td>
  </tr>
  <tr>
    <td>Messaging Layer</td>
    <td>Describes communication between systems of record and systems of record and public common frame of reference through message queues.</td>
    <td>The messaging layer MUST implement a broker-less peer to peer messaging protocol.  No prescription on what protocol to be implemented.</td>
  </tr>
  <tr>
    <td>Privacy Layer</td>
    <td>Describes mechanisms to ensure counterparties confidentiality and shielded private transactions.</td>
    <td>The privacy layer MUST implement a zero-knowledge protocol. No prescription on type of ZK protocol to be implemented.</td>
  </tr>
  <tr>
    <td>Agreement Execution Layer (abstracted from Smart Contract Layer)</td>
    <td>Describes the functionalities, events and terms required for baselining.</td>
    <td>The Agreement Execution Layer MUST control and execute XYZ functionalities, events and terms. No prescription on usage of smart contracts as it is blockchain-technology specific.</td>
  </tr>
  <tr>
    <td>Securitiy Considerations</td>
    <td>Describes security topics that should be important in Baseline implementations but that are NOT requirements. </td>
    <td>Flexible. Depends on the security item discussed.</td>
  </tr>
  <tr>
    <td>Conformance</td>
    <td>Described the conformance clauses and tests required to achieve baseline compliant implementations.</td>
    <td>Conformance clauses need to be testable.</td>
  </tr>
</table>

* Baseline API Spec document

<table>
<tr>
    <th>Component</th>
    <th>Component Description</th>
    <th>Proposed Abstraction level</th>
  </tr>
  <tr>
    <td>IBaselineRPC</td>
    <td>Describes interface that provide functions to interact with Agreement Execution Layer. </td>
    <td>No further abstraction needed. To be taken from baseline/core/api/.
</td>
  </tr>
  <tr>
    <td>IRegistry</td>
    <td>Describes interface that provide functions to manage workgroups, organizations and users. </td>
    <td>No further abstraction needed. To be taken from baseline/core/api/.</td>
  </tr>
  <tr>
    <td>IVault</td>
    <td>Describes interface that provide functions to manage vaults and keys.</td>
    <td>No further abstraction needed. To be taken from baseline/core/api/.</td>
  </tr>
  <tr>
    <td>IBlockchainService</td>
    <td>Describes interface that provide functions for Blockchain clients.</td>
    <td>IFF common frame of reference is a blockchain. No further abstraction needed. To be taken from baseline/core/.</td>
  </tr>
</table>

* Mainnet Spec document

<table>
<tr>
    <th>Component</th>
    <th>Component Description</th>
    <th>Notes</th>
  </tr>
  <tr>
    <td>Maturity & Adoption/Usage</td>
    <td>Define measurable indicators of a mature and widely adopted Mainnet.</td>
    <td>Factual qualitative and quantitative indicators. No abstraction.</td>
  </tr>
  <tr>
    <td>Safety Properties</td>
    <td>Describes the guarantees needed that XYZ will not happen.</td>
    <td>For example we may not want Mainnet roadmap and development to be kept under secrecy.</td>
  </tr
  <tr>
    <td>Liveness Properties</td>
    <td>Describes the guarantees needed that XYZ must happen.</td>
    <td></td>
  </tr>
  <tr>
    <td>Security</td>
    <td>Describes security requirements  - fault tolerance, encryption, security mediation, private transactions & permissionning, professional auditing.</td>
    <td></td>
  </tr>
  <tr>
    <td>Operations & Management</td>
    <td>Describes the functional requirements/components enabling reliable and cost effective operations on the Mainnet (stats and status, error hospital, services deployment etc). </td>
    <td></td>
  </tr>
  <tr>
    <td>Governance</td>
    <td>Describes the governance requirements and mechanisms for coordination.</td>
    <td></td>
  </tr>
  <tr>
    <td>Performance</td>
    <td>Define measurable indicators for high availability, scalability, block formation time, finality time etc.</td>
    <td>Factual qualitative and quantitative indicators. No abstraction.</td>
  </tr>
</table>

**Comment by Consianimis** [comment]
To faciliate review of comments/feedback/question, it would be helpful to adopt this format:

- Document > Component > Component Description ¦ Proposed Abstraction level
- Feedback

For instance:

-  Baseline CORE Spec document > Privacy Layer > Proposed Abstraction level
-  I am not sure that this is the appropriate abstraction level because ABC, I propose XYZ.

**Comment by Therecanbeonlyone1969** [comment]
@Consianimis @humbitious 

**Key Scope Question**: Are we requiring only permissionless DLT networks or do we allow also public permissioned and private DLT networks? 

For the below and for simplicity, I am assuming the current permissionless DLT context only.

Please, see my suggestions below. Changes are bolded.

Deliverables:
The Baseline Standard is comprised of three documents:

1. **The Baseline CORE Specification Document: The document describes the minimal set of business and technical prerequisites, functional and non-functional requirements, together with a reference architecture that when implemented ensures that two or more systems of record can synchronize their system state over a permissionless public Distributed Ledger Technology (DLT) network.**
2. The Baseline API **& Data Model Specification** Document: The document describes the Baseline programming interface and expected behaviors of all instances of this interface **together with the required programming interface data model.**
3. **Permissionless DLT Requirements and Assumptions** Document: The document describes **required and assumed properties and qualities of a permissionless singleton state machine and its operating environment for such a permissionless DLT to safely synchronize two or more enterprise systems of record.**

Notes: The key change is around Mainnet. We cannot create a standard for permissionless networks as those networks are typically fit-for-purpose, see Bitcoin. We can only specify requirements and make assumptions that might or might not be true since we do not control the operating environment, for example, assumptions about transactions being or not being front-run or censored. Hence, the suggested rewording.

Scope

CORE Specification Document:

- Messaging Layer -> Proposed Abstraction Level -> Why does the messaging have to be broker less and p2p when I instantiate the protocol only between a trusted set of entities. something like Kafka would be suitable as well. We should specify which characteristics a message layer must have vs. should have vs. may have.

- Privacy Layer ->  Proposed Abstraction Level -> ZKPs are not the only privacy-preserving method. What about MPC? or TEEs So the same argument as above. Recommend the focus should be on characteristics.

- Governance layer -> We need a governance layer since we have Organization APIs

API & Data Model Specification Document:

- Need a section for a data model

Permissionless DLT Requirements & Assumptions Document:

- I would add network topology since it is kinda important where nodes operate, how many there are, mining pools and their policies etc.
- We need to concretize Operations & Management and, maybe, reword to Network Operations & Management since this comprises messaging, mempools etc.

**Comment by breakpointer** [comment]
This is a great start! However, I think the scope is too broad. Since scope creep is inevitable so if we start as small as possible the spec might have a fighting chance. 😄 

Looking at what is currently in the issue above I would avoid anchoring to the names of folders/packages/etc.. in the current v0.1 code. It's important at this stage to think more broadly about the areas of Baseline that might benefit from what we're trying to do here by creating a more concrete protocol specification. For example, anything related to the currently named "API layer" or "Baseline API" should be removed. It might benefit the development of the spec to outline areas more in terms of the "jobs to be done" and not a particular technology, since many could satisfy. Also, and this might be controversial, but does the spec need any mention of a certain main-net? What is its "job" in Baseline exactly? Is there any part of the Baseline protocol that really cares what kind of network it's on? 

Another angle to consider, as a thought experiment, what would it require to "Baseline" something on paper (yes, actual dead tree paper) if none of this technology existed. IF we can distill Baseline down to the essence of it first, and then add in key technology constraints (a.k.a. specifications) as needed I think we'll have a standard that is easier to understand, adopt, and mature over time.

**Comment by Consianimis** [comment]
@breakpointer , @Therecanbeonlyone1969  Thank you for your feedback. I think they surface the need to address two different demands:

1. Actionable requirements for the enterprise blockchain & DLT communities. The builders and developers that already know that those are the technologies they want to use for ‘Baselining’ and who will benefit from having specifications to do it in a compliant way.  One opinion could be that currently, this may well be our core audience so providing specifically to them may not be inappropriate (for example with an API spec for those ready to build on Mainnet).

2. Saying that, it was always clearly communicated that ‘Baselining’ is a methodology that is technology agnostic and therefore the OASIS standard need to provide requirements for a much wider, unidentified audience who is interested in the set of principles and techniques required  to use a lambda state machine as a common frame of reference between any kind of database or state machines as a way to automate processes.

@humbitious, my questions are:

- Should we make an exclusive choice between those two demands? We either do (1) or (2).
- If not, we will eventually do both but what demand should we prioritize on the short term and why?
- If yes, should we only be doing (2) considering that this is a Ethereum-Oasis project and there is an expectation to deliver an OASIS standard at the end of it?
- Or is there another middle ground approach that we need to think of.

**Comment by Therecanbeonlyone1969** [comment]
@Consianimis my 2 Wei are that we can do both (1 and 2) since we have (3) different documents and all of them can be written simultaneously by 3 different working groups.  

As I stated before, I can write the public DLT doc without ever referencing a single DLT stack -- see an example here (DLT section for specificity) https://9db836f3-ccf1-4990-82a6-3036d6f8890a.filesusr.com/ugd/d18226_545a1ea92d814206957a0d4d41a73a17.pdf

@breakpointer -- I hear your concern and understand where you are coming from. My 2 Wei here: Based on my W3C experience on DIDs and VCs we need a data model spec. And based on my DIF and EEA spec work we also need an API spec. If you do not have both then any production implementation will block any changes on the more abstract functional spec that might break their custom APIs and data model. That is a scenario we should try to avoid at all costs. Furthermore, there are already existing APIs and data models in existing implementations and I think it would be prudent to standardize them as quickly as possible rather than have things going on in the wild.

**Comment by danielnorkin** [comment]
Baseline API Spec document > Data Model
I would be interested to see the Data Model framework @Therecanbeonlyone1969 suggested. Anything to make dynamic functionality will be extremely helpful to implement across different use case

**Comment by Therecanbeonlyone1969** [comment]
> Baseline API Spec document > Data Model
> I would be interested to see the Data Model framework @Therecanbeonlyone1969 suggested. Anything to make dynamic functionality will be extremely helpful to implement across different use case

@danielnorkin ... each API has its own data model that is correct. Then you have message formats, then you have offchain storage, then you have onchain storage with duplication of data or the same data in different formats e.g. hash of or base64url encoding etc. -- hence, my statements above. This needs to be specified what is the required vs optional data set at each layer of the stack

**Comment by Consianimis** [comment]
Revised Standards and Specifications scope discussed during 2020.09.15 working session (issue #117) is available here: https://docs.google.com/presentation/d/1flLuI-fsvR6Ae0gIB0GjNO06MEJm98ETSjj-xc9ZhqI/edit#slide=id.g9555c8d89d_0_31

**Comment by Consianimis** [comment]
Scope reviewed and updated. Kick off completed.
